persistence true
persistence_location /mosquitto/data/

listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_anonymous true

# ACLs are not required for demo; comment out include_dir
# include_dir /mosquitto/config/acls

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all
log_timestamp true
